### ISSUE TITLE
cannot import veryfi email :'(

### ISSUE THREAD

**Issue by Nanumiric123** [un33k/python-emailahoy#2]
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    from emailahoy import query_mx
  File "emailahoy.py", line 2, in <module>
    from emailahoy import VerifyEmail
ImportError: cannot import name VerifyEmail

**Comment by un33k** [comment]
You must have emailahoy on you Python path. 

Please install as per instruction in read me file. 

## Val
